### ISSUE TITLE
[to feat] 2.28-3.11 Todo List

### ISSUE THREAD

**Issue by moon9ua** [economicus/economicus-fe#29]
youjeon님께서 작성한 투두리스트입니다.

- [x] 1. 재무상태 모달 체크 해제시 해당 자료 전송 되지않게 버그 수정
- [x] 2. 재무상태 모달 체크 해제시 슬라이더 disable 이 아니라 미표시
- [x] 3. 재무상태 모달 슬라이더에 현재 상태 표시 툴팁 추가
- [x] 4. 재무상태 모달내 이름들을 key-value형태로 제대로 표현(+단위 표시)
- [x] 5. Make Model 클릭시 로딩 상태 표시 및 추가 입력 방지
- [x] 6. Make Model 클릭시 모델명 중복일때 에러 핸들링
- [x] 7. 재무상태 아래에 현재 선택한 체크박스들 표시(사업분야는 반대로 제외한것들을 표시하면 좋을듯?)
- [x] 8. 모달 창에 확인 버튼 추가. 바깥 클릭과 동일하게 닫더라도 ux를 생각했을때 필요해보임
- [x] 9. 모델 표시 칸 데이터 표준화 및 상단 머리글 행 이름 제대로 표현
- [x] 10. 모델 표시 칸 저장버튼 클릭시 나오는 모달 수정해서 모델 상세페이지로 이동할수있게 변경
- [x] 11. 모델 표시 칸 삭제 버튼 클릭시 백엔드에 삭제 내역 전송
- [x] 12-1. 모델 상세페이지 ui 제작
- [ ] ~12-2. 모델 상세페이지 백엔드에서 데이터 수신해서 표시할수있게 작업~
- [x] 13-1. 회원가입 페이지 ui 제작
- [x] 13-2. 회원가입 페이지 실제로 백엔드와 연동하여 동작 할수 있게 수정
- [x] 14-1. 모델 종목 페이지 ui 제작
- [ ] ~14-2. 모델 종목 페이지 실제로 백엔드와 연동하여 동작 할수 있게 수정~

**Comment by JeonYoungHo-youjeon** [comment]
서브태스크 나누고 모델 종목 페이지 제작 부분 추가했습니다.

**Comment by moon9ua** [comment]
* [x] 15. 로그인 유지 구현 #28
* [x] 16. 로그인 경고 해결 #23

**Comment by hermin9804** [comment]
- [ ] 17. 실험실 재무상태 모달 최대, 최소값 표시 이슈료 인한 UI변경

**Comment by hermin9804** [comment]
- [x] 17. 재무상태 모달 UI 변경 #42 -> mher

**Comment by JeonYoungHo-youjeon** [comment]
- [ ] ~18-1. 유저 전략 리스트 페이지 ui 제작 -> mher (19번 이슈로 병합)~
- [ ] ~18-2. 유저 전략 리스트 페이지 백엔드와 연동 (19번 이슈로 병합)~

**Comment by hermin9804** [comment]
- [x]  19-1. 개인 프로필 페이지 ui 제작 -> mher
- [x]  19-2. 개인 프로필 페이지 백엔드와 연동 -> mher

**Comment by moon9ua** [comment]
* [x] 20. 네비게이션 구성 수정 및 로그인 라우터 분기

**Comment by JeonYoungHo-youjeon** [comment]
전체 작업 완료 및 병합으로 이슈 닫겠습니다.
